### PR TITLE
Reference the linkedlist lib directly in package.json

### LINKED ISSUE #4: no dynamic export
Would it be possible to remove the dynamic module.exports so that this can be used with webpack? ES6 module syntax prohibits dynamic exports.

### PR DESCRIPTION
**Pull request by jeckhart**
Reference the linkedlist lib directly in package.json to remove dynamic exports for webpack and es6.

Fixes #4

### CODE REVIEW

**Comment by jeckhart** [comment]
Note: the travis checks fail because some of the dependent libs no longer support older versions of node (0.6 and 0.8). I recommend removing support for those versions of node at this point.

**Comment by kilianc** [comment]
👏 

Since you're there could you add node 7 and 6 as well to the test suite?

**Comment by jeckhart** [comment]
Yep, done!

**Review by kilianc — APPROVED** [review]

**Comment by kilianc** [comment]
@jeckhart immensely grateful for your time and for using my library.

**Pull request merged**
